version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "build and test"
          command: "./gradlew clean test"

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
